
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-09
owner: ucsb-cs156-f25
repo_name: team01-f25-09
pull_requests: [{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oyararbas-menuitemreview-delete","number":74,"title":"Added DELETE endpoint for a specific record in MenuItemReview table","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/74"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-RecommendationRequest-add-delete","number":73,"title":"lc - Add DELETE endpoint for a specific record in RecommendationRequest table","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/73"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"viktorinkov-add-article-delete","number":72,"title":"Viktorinkov add article delete","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/72"},{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oyararbas-menuitemreview-putedit","number":71,"title":"Added put (edit) for single record in MenuItemReviewTable","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/71"}]
