
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-09
owner: ucsb-cs156-f25
repo_name: team01-f25-09
pull_requests: [{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"samc005-UCSBDiningCommonsMenuItem-add-DELETE","number":68,"title":"samc005-UCSBDiningCommonsMenuItem-add-DELETE","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/68"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-RecommendationRequest-add-get","number":67,"title":"lc: added GET /api/RecommendtionRequest?id = 123 endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/67"},{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oyararbas-menuitemreview-getshow","number":66,"title":"Added GET (show) endpoint for single record in MenuItemReview table (#28)","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/66"}]
