
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-09
owner: ucsb-cs156-f25
repo_name: team01-f25-09
pull_requests: [{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"samc005-UCSBDiningCommonsMenuItem-add-GET","number":61,"title":"step 4: add GET endpoint for single record","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/61"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-delete","number":60,"title":"dk - add delete endpoint for helprequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/60"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-RecommendationRequest-createController","number":59,"title":"lc - Create RecommendationRequestController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/59"}]
