
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-09
owner: ucsb-cs156-f25
repo_name: team01-f25-09
pull_requests: [{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-organization-get-by-id","number":49,"title":"PC - add GET by id in Organization","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/49"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-HelpRequest-create-controller","number":48,"title":"dk - create HelpRequest controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/48"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"david-GET-POST","number":47,"title":" DB - Create Organizations Controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/47"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"samc005-UCSBDiningCommonsMenuItem-create-controller","number":46,"title":"UCSB dining commons menu items - create controller/test, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-09/pull/46"}]
